# Sample config file
# The values mentioned are the default values

[logging]
directory = "log"
active_file_name = "out.log"

[rotation]
max_lines = 100
max_file_size_bytes = 1000000

[flushing]
time_interval_secs = 5

[rollup]
file_rename_format = "TBD"

[misc]
prepend_timestamp = false
expose_stats_endpoint = false
