# Sample config file
# The values mentioned are the default values

[logging]
directory = "log"
active_file_name = "out.log"

[rotation]
max_lines = 100
max_file_size_bytes = 1000000

[flushing]
time_interval_secs = 5

[rollup]
file_rename_format = "TBD"

[misc]
# Populate the following variable if you want to
# prepend your log line with a predefined text.
# There are some template values you can use too.
# {{.Timestamp}} expands to a timestamp in RFC822 format
# {{.UnixTimestamp}} expands to a unix epoch timestamp to nanosecond precision
#
# Example -
# prepend_value = "[app_name]- "
# prepend_value = "[app_name] {{.Timestamp}}- "
prepend_value = ""

expose_stats_endpoint = false
