version: 2
jobs:
 one:
   docker:
     - image: circleci/golang:1.12
   steps:
     - checkout
     - run: echo "A first hello"
     - run: sleep 25
 two:
   docker:
     - image: circleci/golang:1.13
   steps:
     - checkout
     - run: echo "A more familiar hi"
     - run: sleep 15
workflows:
 version: 2
 one_and_two:
   jobs:
     - one
     - two
